//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmployeeInfo
    {
        public int ID { get; set; }
        public string LoginName { get; set; }
        public string LoginPassword { get; set; }
        public string EmployeeHead { get; set; }
        public Nullable<int> Sex { get; set; }
        public Nullable<long> IDNumber { get; set; }
        public string BirthDay { get; set; }
        public Nullable<long> Phone { get; set; }
        public string Email { get; set; }
        public string EmployeeAddress { get; set; }
        public string Degree { get; set; }
        public Nullable<int> PostID { get; set; }
        public Nullable<int> DeptID { get; set; }
        public string EmployeeProfile { get; set; }
        public Nullable<System.DateTime> Hiredate { get; set; }
        public Nullable<int> Wage { get; set; }
    }
}
