//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class testEntities : DbContext
    {
        public testEntities()
            : base("name=testEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Calendar> Calendar { get; set; }
        public DbSet<Dept> Dept { get; set; }
        public DbSet<Employee_PermissionInfo> Employee_PermissionInfo { get; set; }
        public DbSet<Employee_RoleInfo> Employee_RoleInfo { get; set; }
        public DbSet<EmployeeInfo> EmployeeInfo { get; set; }
        public DbSet<GetEmailMessages> GetEmailMessages { get; set; }
        public DbSet<Payroll> Payroll { get; set; }
        public DbSet<PermissionInfo> PermissionInfo { get; set; }
        public DbSet<PostInfo> PostInfo { get; set; }
        public DbSet<RoleInfo> RoleInfo { get; set; }
        public DbSet<RoleInfo_PermissionInfo> RoleInfo_PermissionInfo { get; set; }
        public DbSet<SalaryRecord> SalaryRecord { get; set; }
        public DbSet<SendEmailMessages> SendEmailMessages { get; set; }
        public DbSet<TimeSheet> TimeSheet { get; set; }
    }
}
