//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class TimeSheet
    {
        public int ID { get; set; }
        public Nullable<int> EmployeeID { get; set; }
        public string OfficeHour { get; set; }
        public string QuittingTime { get; set; }
        public string Check_inTime { get; set; }
        public string SignBackTime { get; set; }
        public Nullable<int> Check_inType { get; set; }
        public Nullable<int> SignBackType { get; set; }
        public string Remark { get; set; }
    }
}
